export default {
   whales: [
      "whale",
      "ocean",
      "marine",
      "mammal",
      "blue",
      "humpback",
      "orca",
      "beluga",
      "sperm",
      "nautical",
      "deep",
      "giant",
      "swim",
      "water",
      "fluke",
      "fin",
      "tail",
      "breach",
      "spout",
      "blowhole",
      "krill",
      "school",
      "pod",
      "feeding",
      "migration",
      "communication",
      "whalebone",
      "calves",
      "oceanography",
      "ecology",
      "conservation",
      "research",
      "marine biology",
      "habitat",
      "whale watching",
      "arctic",
      "antarctic",
      "oceanic",
      "whale shark",
      "beached",
      "whaling",
      "cetacean",
      "sustainable",
      "marine sanctuary",
      "North Atlantic right whale",
      "toothed whale",
      "baleen whale",
      "singing",
      "blubber",
      "seafloor",
      "swimming patterns",
      "spyhopping",
      "sonar",
      "migration routes",
      "endangered",
      "species",
      "conservation efforts",
      "sustainable practices",
      "marine life",
      "submarine",
      "sea",
      "moby dick",
      "harpoon",
      "whale oil",
      "whalebone corset",
      "whale song",
      "whale watching tour",
      "hunting",
      "seafaring",
      "captain",
      "ship",
      "whaler",
      "whale catcher",
      "seafarer",
      "shipmate",
      "sailor",
      "navy",
      "whale skeleton",
      "whale exhibit",
      "whale museum",
      "nautical chart",
      "navigational tools",
      "marine life conservation",
      "whale protection",
      "ecosystem",
      "whale researcher",
      "marine mammal biologist",
      "oceanic exploration",
      "whale symbolism",
      "whale myth",
      "whale deity",
      "whale folklore",
      "whale art",
      "whale sculpture",
      "whale painting",
      "whale conservation organization",
      "whale rescue",
      "whale conservation program",
      "whale documentary",
      "whale education",
      "whale tail sculpture",
      "whale-themed merchandise",
      "whale-themed jewelry",
      "whale-watching season",
      "whale migration observation",
      "whale tracking",
      "whale research vessel",
      "whale biologist expedition",
      "whale song recording",
      "whale pod behavior",
      "whale family structure",
      "whale nursery grounds",
      "whale anatomy"
   ],
   everything: [
      "one",
      "two",
      "three",
      "four"
   ]
}
